sudo: required

services:
  - docker
language: java
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - gradle jar
  - gradle copyToLib
  - echo "$DOCKER_PASSWORD" | docker login $DOCKER_HOST -u "$DOCKER_USERNAME" --password-stdin
  - docker build --tag registry.reticent.io/eevee .
  - docker push $DOCKER_HOST/eevee