sudo: required

services:
  - docker
language: java
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - gradle jar
  - gradle copyToLib
  - echo "$DOCKER_PASSWORD" | docker login $REGISTRY_HOST -u "$DOCKER_USERNAME" --password-stdin
  - docker build --tag $REGISTRY_HOST/eevee .
  - docker push $REGISTRY_HOST/eevee